koverstreet/bcachefs-tools

- cmd_device.c
If a disk is absent, there is no way to remove it from the filesystem.
Add the possibility to remove devices by id, to allow removal of missing
disks.
Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>
> cmd_device_remove: allow removal by device id

- INSTALL
- Makefile
> New install distros

- include/linux/slab.h
Fix a ASan complaint.
Signed-off-by: Yuxuan Shui <yshuiv7@gmail.com>
> Make sure aligned_alloc size is a multiply of alignment

- cmd_fsck.c
looks like an extra dash snuck in...
> correct flag listing in fsck help text

- smoke_test
- tests/util.py
- tests/valgrind-suppressions.txt
also grab environment variable for pytest if set
> adds Valgrind suppression to ignore userspace-rcu leak

- linux/blkdev.c
linux/blkdev.c was originally implemented as sync io, and later converted to aio in [this commit](https://github.com/koverstreet/bcachefs-tools/commit/e41920e6036c3fb6b91edac44a56630cf13d8027).
@iav tested this here:
https://github.com/iav/bcachefs-tools/runs/3853411092
> Fall back to synchronous io when kernel doesn't support aio.

- bcachefs.8
Update manpage to follow --label and --compression updates
> Update manpage to follow --label and --compression updates

- cmd_device.c
Signed-off-by: Daniel B. Hill <daniel@gluo.nz>
> fix labels not applying

- bcachefs.8
When group was switched to label it looks like this got missed.
> fix example

- bcachefs.8
Fix man for device set-state command
Signed-off-by: Igor Velkov <iav@iav.lv>
> Fix man for device set-state command

- c_src/cmd_key.c
Similar to the same option with luks. Of course,
one can simply wrap bcachefs tool with a script and expect, but this is a nicer way of doing things.
It's the first time, I contribute C code to any project related to the kernel. Apologies, if I don't comply to standards.
I tried my best being a good neighbor. Please be easy on me.
See #210.
> Add option to read passphrase from a keyfile

- c_src/cmd_key.c
- c_src/crypto.c
- c_src/crypto.h
- src/commands/cmd_mount.rs
- src/key.rs
- tests/test_basic.py
Apply naming convention: passphrase->unlock->key->decrypt->fs
> Improve encryption/decryption naming convention

- src/bcachefs.rs
I think writing to a const value in Rust invokes undefined behaviour. The `to_mut` function in `bcachers.rs` looked a little suspect so I made a small reproduction and ran [MIRI](https://github.com/rust-lang/miri) on it. It confirmed my suspicions:
> error: Undefined Behavior: trying to retag from <7013> for Unique permission at alloc2678[0x0], but that tag only grants SharedReadOnly permission for this location
You can see the reproduction here:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c6d843c3a853cba49db4c20548330c36
Click Tools > Miri to run it
This PR aims to address this. I removed the redundant initial clone of the args and shuffled the argv processing in order to avoid casting the const pointer to a mutable one.
Ideally, after the C command ran we'd …
> Avoid casting away const when processing C command args

- src/commands/cmd_mount.rs
If we pass a symlink for a single device node we fail to locate the device node.  Canonicalize the device node before we try to read up the superblock.
This allows the following to work.
``` # bcachefs mount /dev/mapper/vg-thinvolume /mnt/lv_thin```
> mount: canonicalize device path for single device node

- .editorconfig
- build.nix
- default.nix
- flake.lock
- flake.nix
A number of changes to make it nicer to work with this project if you're using a Nix workflow.
> Flake overhaul

- .editorconfig
- .github/workflows/nixos.yml
just to check if this fixes the CI.
> github action fix

- Cargo.lock
- Cargo.toml
- c_src/cmd_key.c
- c_src/crypto.c
- c_src/crypto.h
- src/commands/mount.rs
- src/key.rs
I think this is somewhat more idiomatic and also adds zeroize, which the current Rust code is missing when handling passphrases.
Please let me know if this is a direction that you like for that code. :)
> Rewrite rust key handling

- src/commands/mount.rs
This one is sort of bad to have missed, ouch.
> fix: evaluate KeyHandle Result

- src/key.rs
- src/wrappers/handle.rs
Fixes a problem I caused in https://github.com/koverstreet/bcachefs-tools/commit/96a346254d6c39d45f816e9c5f903a2efa3d1c0d
> Fix subvolume commands

- src/commands/subvolume.rs
Which is probably not the case when you want to create a subvolume in that path.
I broke this in the last patch to add canonicalizing...
> fix(subvol): canonicalize requires path to exist

- .editorconfig
- src/commands/logger.rs
- src/key.rs
Picked out from the nixos-tests PR because these be should be merged regardless of the rest.
> Fixes from nixos-tests

- Makefile
> Use the AR variable in Makefile

- bcachefs.8
- c_src/cmd_option.c
The instructions confused me a bit so I fixed them.
> Change lingering set-option texts to set-fs-option

- bcachefs.8
Closes #343
Fixes: 52b9e813 ("Rename option commands")
> man: setattr has been renamed to set-file-option

- INSTALL.md
While it, shorten zypper command and reformat.
> docs: Add fuse package on openSUSE

- debian/changelog
add version change for debian package, 
fix wrong date format in previous deb version record
> add version change for debian package

- .github/workflows/deb-publish.yml
> APT Readme: use different sentinels in nested cat blocks

- .github/workflows/deb-buildd.yml
- .github/workflows/deb-orchestrator.yml
- .github/workflows/deb-publish.yml
- .github/workflows/deb-src.yml
- debian/control
- debian/tests/control
- debian/tests/kernel-smoke-test
- debian/tests/kernel-smoke-test.00.single
- debian/tests/kernel-smoke-test.01.single-mount
- debian/tests/kernel-smoke-test.02.single-populate
- debian/tests/kernel-smoke-test.03.single-persists
These tests require qemu, and it's somewhat tricky, i haven't quite figured out the incantation
that works for Github's aarch64 workers.
I'm also unsure how to make them work for ubuntu builds.
Since debian stable's kernel is too old, as discussed, i'm disabling PPA for it.
> Debian / PPA: add autopkgtests, run them for debian amd64 jobs

- .github/workflows/deb-buildd.yml
- .github/workflows/deb-orchestrator.yml
- .github/workflows/deb-publish.yml
- .github/workflows/deb-reprotest.yml
- .github/workflows/deb-src.yml
- debian/control
TLDR: instead of running the entirety of the job in the container, start a detached container, and manually run each step in detached container. This allows to run stuff outside of container.
> Deb PPA rewrite, adding packages for ppc64el
