koverstreet/bcachefs-tools

initramfs/script

This PR improves the initramfs script used to unlock encrypted bcachefs root devices.
- Use plymouth if available, otherwise fall back to text consoles.
- Resolve the root device, so it can be specified by UUID, label, etc.
- Only try to unlock the device 3 times before opening a shell (or rebooting if panic= is on the kernel cmdline).
- If the user runs into an issue, this allows them to try to fix it from an initramfs shell immediately instead of having to physically reboot the box and add break= to the kernel cmdline.
- Don't do anything if the ROOTFSTYPE is not bcachefs (and not empty).

Initramfs script improvements for encrypted bcachefs root filesystems

---

Makefile
bcachefs.8
bcachefs.c
cmd_version.c
cmds.h

It would be nice to have a way to tell whether a compiled version of the bcachefs tool is out of date, so I added a version command to print where the tool was built from.
By default it uses git describe to generate a version string (E.g. 0.1-355-ga5d94ce), but will fall back to the string "0.1-nogit" if git describe fails.
You will need to create an annotated tag somewhere for git describe to work (or change the git describe arguments).
The version string can also be overridden on the make command-line with the VERSION= parameter.

Add version command

---

cmd_migrate.c

The attr/xattr.h doesn't exist on the newer versions of attr and can be replaced throught the in glibc included sys/xattr.h

Replaces attr/xattr.h include

---

bcachefs.c
initramfs/hook

Also, don't print an error message when running "bcachefs --help".

Add chacha20 and poly1305 modules to initramfs

---

linux/shrinker.c

If no shrinkers have been registered, there is no reason to read /proc/meminfo.
This allows some commands to run without needing the /proc filesystem to be mounted including format, show-super, unlock, --help, and version.
Since list_empty only does a simple pointer comparison, it seemed unnecessary to take the shrinker_lock.
(See [urcu/list.h](https://github.com/urcu/userspace-rcu/blob/master/include/urcu/list.h#L184))

Don't read meminfo if there are no shrinkers

---

cmd_format.c
libbcachefs.c

This now prints "(none)" instead of uninitialized data for disks that aren't in a disk group.
The human-readable targets are now printed instead of just a number.  E.g. "none" or "Group 1 (slow)" or "Device 3 (461f2a5f-a199-4887-aed9-f2ffd0372f66)" instead of just "3" or "257".
Also fixed the usage message and getopt string for the format command (-e is already there as an alias for --error_action, -g wasn't working for --group, and there isn't a -t anymore).
Finally, removed some superfluous strdup() calls which were never being freed (in this case the strdup was unnecessary since the argv[] strings will be available as long as the program is running).

Nicer group and target show-super output

---

cmd_format.c
debian/bcachefs-tools.dirs
debian/bcachefs-tools.postinst
debian/bcachefs-tools.postrm

After the bcachefs-tools debian package is installed or uninstalled, we should update the initramfs so the bcachefs utility is added or removed from it accordingly.
This also fixes the -g short opt for the format command to create a disk group.
Finally, make install creates all the necessary directories, so the debian/bcachefs-tools.dirs file is unnecessary.

 Update initramfs after .deb install or uninstall

---

.gitignore
Makefile
initramfs/hook

A bunch of small tweaks to the top-level Makefile along with a small change to the top-level .gitignore and to the initramfs hook.
* Don't ignore other .gitignore files that are added
* Added a comment about the bcachefs utility to the initramfs hook
* To give a better idea of what the installed hook looks like when you're just looking at the source file
* make install was updated to remove the last 2 commented out lines, so the installed file will end up similar to before this commit:
```
copy_exec /usr/local/sbin/bcachefs /sbin/bcachefs
```
* Replaced `mkdir -p` in favor of `install -D` in the install target
* Don't use delayed expansion for the pkg-config output so that pkg-config only gets called twice total instead of once per compile or link command, also changed the command to …

Makefile, gitignore, and initramfs hook improvements

---

INSTALL
Makefile
debian/control
debian/copyright
debian/watch

- Remove libattr from the Debian dependency list (and from the dependencies in INSTALL)
- Abort compilation early if one of the pkg-config commands fails (doesn't print anything)
- Updated the bcachefs URLs in the Debian control, copyright, and watch files.

Update debian URLs and remove libattr from dependencies

---

INSTALL

Debian Buster (currently "stable") uses libfuse3 version 3.4
which doesn't have some of the logging features which
`cmd_fusemount.c` uses. libfuse v3.7 used by Debian Bullseye
works fine.
If you want, I can add install information for some more distros (maybe Arch and CentOS). I am I using Docker to verify the build processes so I can PR those files if they would be helpful as well.

Add fuse3 dependency information to INSTALL

---

INSTALL
Makefile

I have been testing the builds with Dockerfile like so:
```Docker
FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y \
build-essential git pkg-config libaio-dev libblkid-dev \
libkeyutils-dev liblz4-dev libscrypt-dev libsodium-dev \
liburcu-dev libzstd-dev uuid-dev zlib1g-dev valgrind
WORKDIR /build
RUN git clone https://github.com/koverstreet/bcachefs-tools.git .
RUN make && make install
```
If you think incorporating these into the repo would be helpful, let me know.
Also, the build (even without fuse) fails on CentOS 7 and 8 (for different reasons). Is there somewhere I should report that? (Using Dockerfile should also make it easily reproducible.)

Install information for more distros

---

include/linux/slab.h

posix_memalign doesn't have the restriction that size must be a multiply
of alignment.
This also reverts the fix in commit f3fdbbfa92defb1f1d12c0038513b69b52baf33e.
Signed-off-by: Yuxuan Shui <yshuiv7@gmail.com>

kmalloc: use posix_memalign

---

bcachefs.8

Since tiering  has long been gone, i've removed it from the man pages and replaced the one example that there was in the man page with disk groups

remove any mention of tier from man pages

---

tests/test_basic.py

Improvements to the 'list' command broke the basic test assertion that the output should be only 2 lines. Now it's 95 lines. This PR fixes this test for now.
Thank you for the great work!

Fixes tests which have broken since 'list' improvements

---

smoke_test
tests/test_basic.py

FUSE support is currently broken, so disable those tests for now.
The "test_basic::test_list" test also had an arbitrarily output length check which was outdated.

Make smoke_test pass

---

cmd_fusemount.c
linux/six.c
smoke_test
tests/test_fuse.py
tests/util.py

Fix various problems blocking the fuse tests from passing:
D -> BCACHEFS_DEBUG was missing
Build was broken on gcc-7.5 (with BCACHEFS_DEBUG)
Missing iter_put calls in cmd_fusemount.c
Also added better checking to detect if the FS entered a bad state during testing.
All but one of the tests pass. The remount test reports memory leaks under valgrind, so valgrind was disabled.

Fix fuse and re-enable smoke tests

---

.gitignore
Makefile
doc/autogen/bcachefs.5.rst
doc/autogen/gen.h
doc/autogen/gen.sh

bcachefs.5.txt has a TODO to include options, this change does the following:
- changes bcachefs.5.txt -> bcachefs.5.md for Github markdown rendering
- adds a macro to translate option definitions from opt.h into a markdown formatted table
- adds `make docs` to the Makefile to automate regenerating markdown tables (to be ran after changing options in `opt.h`)
- macro expansion filtering
If this approach seems reasonable, I can clean up the formatting prior to merge.

Added markdown doc option generation using preprocessor

---

tests/test_basic.py

fixes: #74 
removes assertion based on arbitrary amount of lines outputted by the bcachefs command

pytest: remove arbitrary assertion

---

.travis.yml
Makefile
smoke_test
tests/conftest.py
tests/test_basic.py
tests/test_fixture.py
tests/test_fuse.py
tests/util.py

Tested with Python 3.9.5:
```
/bcachefs-tools ~ ./smoke_test
/bcachefs-tools ~ make check
/bcachefs-tools ~ pytest-3
/bcachefs-tools ~ pytest-3 tests
/bcachefs-tools/tests ~ pytest-3
```
- Replace depreciated tempfile with mktemp in smoketest.
- Remove unused pytest imports and variables.
- Make path lookup less fragile. Allows pytest to run from any cwd.
- Prevent exeptions caused by calling functions/methods on None objects.
- Disable fuse tests in smoketest. These are broken and add noise.
Signed-off-by: Brett Holman <bholman.devel@gmail.com>

Clean up smoketest and pytests.

---

include/linux/blkdev.h

Kernel definition:
```
holmanb@arc:~/workspace/bcachefs > grep BIO_MAX_VECS include/linux/bio.h 
#define BIO_MAX_VECS		256U
```
This cleans up the following gcc warning:
```
libbcachefs/io.c: In function ‘bch2_write_bio_alloc’:
include/linux/kernel.h:108:17: warning: comparison of distinct pointer types lacks a cast
108 |  (void) (&_min1 == &_min2);  \
|                 ^~
libbcachefs/io.c:785:10: note: in expansion of macro ‘min’
785 |  pages = min(pages, BIO_MAX_VECS);
|          ^~~
```

make BIO_MAX_VECS unsigned, like the kernel definition

---

Makefile

Currently there are "no rst2man found!" and no man build on debian and ubuntu. 
I propose a fix. 
@firestack

fix "no rst2man found!" build error on debian and ubuntu

---

bcachefs.c
cmd_data.c
cmd_device.c
cmd_fs.c
cmd_subvolume.c
cmds.h

The device, data, fs, and subvolume subcommands currently print out a
generic usage message. Make these more specific.
New output:
```
> ./bcachefs device
bcachefs device - manage devices within a running filesystem
Usage: bcachefs device <CMD> [OPTION]
Commands:
add                     add a new device to an existing filesystem
remove                  remove a device from an existing filesystem
online                  re-add an existing member to a filesystem
offline                 take a device offline, without removing it
evacuate                migrate data off a specific device
set-state               mark a device as failed
resize                  resize filesystem on a device
resize-journal          resize journal on a device
Report bugs to <linux-bcachefs@vger.kernel.org>
> …
```

Add more specific subcommand usage messages

---

bcachefs.c

`bcachefs fs usage` now works again, and help messages for sub commands for `device`, `data` and `subvolume`

Fix sub commands not triggering without arguments 

---

Makefile

Sometimes end-user tools create .c files e.g. ccls.
Signed-off-by: Daniel B. Hill <daniel@gluo.nz>

Makefile: We need to exclude hidden folders

---

libbcachefs.c

In bch2_format(): recompute mi after each sb modification: its location in memory may have changed due to reallocation.
This fixes an issue where labels were not assigned (because they were written to an undefined part of the heap instead of the superblock).

Fix heap corruption in bcachefs format

---

Makefile

While setting up a new laptop I noticed a missing dependency check.

Add libkeyutils to the dependency checks

---

tests/valgrind-suppressions.txt

For context, here are the "exact matches" proposed by Valgrind:
Rebalance leak suppression:
```
E           {
E              <insert_a_suppression_name_here>
E              Memcheck:Leak
E              match-leak-kinds: possible
E              fun:calloc
E              fun:calloc
E              fun:allocate_dtv
E              fun:_dl_allocate_tls
E              fun:allocate_stack
E              fun:pthread_create@@GLIBC_2.34
E              fun:kthread_create
E              fun:bch2_rebalance_start
E              fun:bch2_fs_read_write_late
E              fun:bch2_fs_read_write_late
E              fun:bch2_fs_start
E              fun:bch2_fs_open
E              fun:cmd_format
E              fun:main
E           }
```
liburcu (which is known to leak):
```
E           {
E …
```

Add valgrind suppressions:

---

include/linux/compiler.h

The musl C library does not define __attribute_const__. Add it to include/linux/compiler.h with a guard to fix build against musl libc.
Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>

Fix build against musl libc.

---

doc/bcachefs-principles-of-operation.tex

This adds additional details about how encryption works in bcachefs, along with a warning regarding snapshots.

Add additional information about encryption

---

cmd_fs.c

also add documentation for -H in help text
fixes #166

cmd_fs: add long parameter --human-readable to usage command

---

cmd_fs.c

Calculate space based on bucket count and bucket_size for data types where no sectors are available.
Tested on a local fs.
Before:
```
ssd.ssd4 (device 4):             sdc              rw
data         buckets    fragmented
free:                          0 B         1266768
sb:                       3.00 MiB               7       508 KiB
journal:                  4.00 GiB            8192
btree:                    4.42 GiB           14003      2.42 GiB
user:                      510 MiB            1223       101 MiB
cached:                    298 GiB          617545
parity:                        0 B               0
stripe:                        0 B               0
need_gc_gens:                  0 B               0
need_discard:                  0 B               1
capacity: …
```

cmd_fs: calculate free space

---

Makefile
fsck/bcachefsck_all_fail.service.in
fsck/bcachefsck_fail@.service.in

These are executables that need to be installed in a non-path location. Most distributions now install these into /usr/libexec, and the path variable for this is LIBEXECDIR, so use that instead.

Makefile, fsck: Use libexec instead of lib

---

fsck/bcachefsck_all.service.in

Correctly generate libexecdir based path for the bcachefsck_all service, like the bcachefsck_all_fail service already does.
---
This, combined with a downstream AUR PKGBUILD change, should fix the services there as well. Not sure if any other distributions need changes to their build process like Arch does.

fix fsck service location

---

build.nix
src/commands/cmd_mount.rs

This syntax does not set `BCACHEFS_FUSE` at all when fuse is disabled, not even to an empty string. [This line](https://github.com/koverstreet/bcachefs-tools/blob/3da247cd20da37a4d3f4d957a30293261c0e38e2/build.rs#L18) only checks if the variable is set, rather than specifically set to a non-empty string.
`cargo doc` was worried that the `<UUID>` text would be an unclosed HTML tag. This seems to render correctly.

Fix nix and docs

---

bch_bindgen/src/lib.rs

Use to_string_lossy in printbuf_to_formatter, which tolerates non-UTF-8 strings (by using replacement characters).
This is used in various Display impls (BkeySCToText was the one that encountered the issue), and allows something like:
bcachefs list --btree dirents
with non-UTF-8 paths.

printbuf_to_formatter: Lossy display of non-UTF-8 printbufs

---

.gitignore
bcachefs

The CLI is now built by Cargo, add a symlink so it can be found at the place it was before so people don't try to run an old binary.

Add bcachefs command compatibility symlink

---

Makefile
initramfs/hook

Now that the bcachefs tool unconditionally includes the mount parts (or more correctly, you cannot build it at all if you don't have Rust), we can call copy_exec on mount.btrfs, to get the symlink installed. In particular, this helps with mounting UUID mounts as /.
See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1060411 for the remaining parts needed in initramfs-tools itself.

Make initramfs hook install mount.btrfs

---

Cargo.toml
bch_bindgen/Cargo.toml

Debian unstable has the current version of these crates:
- errno: 0.4
- udev: 0.8 (currently in NEW)
- memoffset: 0.6.5
- paste: 1.0.8
- bindgen: 0.66.1
Loosening the versions a bit (some up, some down) allows Debian to build the Rust parts.

Loosen dependencies of Rust crates

---

Makefile

Make clear that LIBEXECDIR is an option.
fixes #215

cosmetic refactoring of Makefile

---

src/commands/cmd_completions.rs
src/commands/cmd_list.rs
src/commands/cmd_subvolume.rs
src/commands/mod.rs

Added a few aliases to a few subcommands I use often, as well as some minor cleanups.
bcachefs subvolume snapshot -> bcachefs subvol snap
Maybe we should also add this to all other subcommands? Would love to hear your thoughts on this.

Add a few subcommand aliases

---

libbcachefs/bcachefs_format.h
src/commands/cmd_mount.rs
src/key.rs
tests/test_basic.py
tests/test_helper.c

As discussed in #211; add a optional flag to specify a key file
- Add key_file option to Cli
- Rework decryption flow logic to first attempt key_file
- Read password from file and pass to decrypt_master_key
Explicity specify '-k' for key_location
Tag @oz123

Add keyfile option to mount

---

c_src/cmd_migrate.c

Better explain which `st_dev` value was expected and which was found and give a hint to why this mismatch might have occurred.

migrate: improve "does not have correct st_dev" error message

---

c_src/cmd_device.c

I noticed `device add -l my-label` wasn't working as expected, so I pulled up the code and noticed some other options weren't setup for short args either.
Also I deleted the (now deprecated, seemingly) `--tier` arg parsing.

Fix device add args

---

bch_bindgen/src/bcachefs.rs
src/commands/mount.rs

If the udev database contains information about bcachefs, utilize it. Otherwise, resort to traversing block devices and checking for bcachefs super blocks.
With this change we no longer get messages like:
```
bcachefs (/dev/sda): error reading default superblock: Not a bcachefs superblock (got magic 00000000-0000-0000-0000-000000000000)
bcachefs (/dev/sda): error reading superblock: Not a bcachefs superblock layout
bcachefs (/dev/sda1): error reading default superblock: Not a bcachefs superblock (got magic 00000000-0000-0000-0000-000000000000)
bcachefs (/dev/sda1): error reading superblock: Not a bcachefs superblock layout
bcachefs (/dev/sda2): error reading default superblock: Not a bcachefs superblock (got magic cd692115-d51f-fa9a-0000-000000000000)
bcachefs (/dev/sda2): error reading …
```

mount: Leverage udev db

---

.github/workflows/nix-flake-update.yml
.gitignore

Adds `nix-flake-update` workflow which updates flake.lock nix dependencies every month.
This ensures builds using up to date dependencies for those using this repository to get bcachefs-tools using nix.

workflows: add monthly flake lock update workflow

---

c_src/cmd_migrate.c
ccan/compiler/compiler.h
debian/changelog
doc/bcachefs-principles-of-operation.tex
doc/bcachefs.5.rst.tmpl
packaging/bcachefs-tools.spec

This PR
- Improves documentation by cleaning up typo and spelling mistakes
Closes https://github.com/koverstreet/bcachefs-tools/pull/129
Adopted from the above PR to remove merge conflict.

treewide: fix typos in docs and comments

---

flake.nix
src/bcachefs.rs
src/commands/list.rs
src/commands/mod.rs
src/commands/mount.rs
src/commands/subvolume.rs
src/key.rs
src/wrappers/handle.rs

Not going to enable `clippy::pedantic` lints by default but there is some good advice in there, especially regarding casting.

Fix pedantic clippy lints

---

src/commands/subvolume.rs

`Path::parent()` returns `Some("")` for relative paths with a single component. The simplest fix is to just canonicalize the paths first.
So I actually had a few misconceptions about this issue, at first I thought it
was because I was doing `bcachefs subvolume create my-subvol` within a bind
mount because it worked when I gave the absolute path from the real mount. Then
I thought it was about `CString` lifetime in FFI, which was also incorrect.
In the end it's pretty simple. The `Path::parent()` API doesn't take into
account any side effects from the file system or check the real path. It just
works on the bytes of the `Path` and gives us a slice into the `Path`.

fix(subvol): make cmds work with relative paths

---

flake.nix

The revision of bcachefs itself is also interesting but having the commit hash of the current repo is more useful.

Make nix package builds have a unique version; dev shell addition

---

flake.nix
src/bcachefs.rs

As reported on IRC:
```
bi_parent_subvol=0
bi_nocow=0
, fixing
bcachefs (nvme0n1p7): Ratelimiting new instances of previous error
bcachefs (nvme0n1p7): check_path(): error EEXIST_str_hash_set
bcachefs (nvme0n1p7): bch2_check_directory_structure(): error EEXIST_str_hash_set
bcachefs (nvme0n1p7): bch2_fsck_online_thread_fn(): error EEXIST_str_hash_set
thread 'main' panicked at src/bcachefs.rs:113:79:
called `Result::unwrap()` on an `Err` value: TryFromIntError(())
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Some C command functions return integers that are larger than 255.

Fix C exit code

---

flake.nix

```bash
nix run github:koverstreet/bcachefs-tools#bcachefs-tools -- version
```
currently fails with
```log
error: unable to execute '/nix/store/1sq2i44fjzbc1vyr81b6xr2m3jnci16k-bcachefs-tools-1.9.5+c60ce81/bin/bcachefs-tools': No such file or directory
```
because meta.mainProgram is not set.
Let's set it and set some other stuff like description and license.

nix: add meta.mainProgram to allow directly running from this repo

---

src/commands/mount.rs
src/key.rs

This would allow to supply the password via the plymouth password input. If systemd-ask-password does not exist or fails to start, falls back to the old-style password request.

Ask for password via systemd-ask-password

---

doc/bcachefs-principles-of-operation.tex

Just fixing some spelling mistakes I noticed while reading.
Also, it seems that the pdf on bcachefs.org isn't up-to-date with the latest copy of `bcachefs-principles-of-operation.tex`, because I noticed [another error](https://github.com/koverstreet/bcachefs-tools/blob/c36b96d4dc1167bb9d38ba5bd594854e99f1ba9b/doc/bcachefs-principles-of-operation.tex#L1055) ("Returs") in [the copy on the website](https://bcachefs.org/bcachefs-principles-of-operation.pdf) was fixed a few months ago (in 18f9526c45e560df26dfadd5bdef7467aab6c0f7). I don't know who updates the website copy or if it's automated, but it might be good to update it soon.

doc: correct some spelling errors

---

Cargo.lock
Cargo.toml
bch_bindgen/Cargo.toml
bch_bindgen/src/bcachefs.rs
src/key.rs

While bcachefs-tools makes good use of many dependencies that have nontrivial code in them, byteorder and memoffset are easily replaced with standard library code nowadays.

Remove trivial deps

---

c_src/tools-util.c

This can prevent data loss as libblkid < 2.40.1 can fail to recognize existing bcachefs filesystems.
Reported on #bcache.

Check for a sufficiently recent libblkid before formatting

---

arch/etc/initcpio/hooks/bcachefs
arch/etc/initcpio/install/bcachefs
arch/etc/mkinitcpio.conf

This adds the necessary initcpio hook for Arch to boot from an encrypted root bcachefs drive/partition. For the time being, the hook is kept in the custom hooks directory (`/etc/initcpio/hooks`) as per the [Arch wiki](https://wiki.archlinux.org/index.php/Mkinitcpio#HOOKS). As things get mainlined and become part of the kernel, we may want to move the hook into the system hooks directory (`/usr/lib/initcpio/hooks`). There is an example of a working `/etc/mkinitcpio.conf` that calls the bcachefs hook when creating a new initramfs with `mkinitcpio -p linux-bcachefs`.

add mkinitcpio hook for Arch and sample /etc/mkinitcpio.conf

---

arch/etc/initcpio/hooks/bcachefs
arch/etc/initcpio/install/bcachefs

Since the mkinitcpio hooks got merged, there were some comments that went unaddressed that improve the quality of the initcpio  scripts, particularly when mounting root device in arch as a UUID as opposed to a `/dev/` node. This has been tested locally on my laptop.

initcpio: small improvements to the mkinitcpio hooks

---

c_src/cmd_key.c
c_src/crypto.c
c_src/crypto.h

This also fixes a bug where the set-passphrase
command failed to derive the key for disks initially formatted with --encrypted and --no_passphrase, due to bch_sb_crypt_init not configuring the KDF params if the passphrase wasn't specified during formatting.
Tested-by: Jérôme Poulin <jeromepoulin@gmail.com>

Fix set-passphrase on --no_passphrase FS

---

src/commands/mount.rs

Just returning a failure exit status makes it hard to tell what the actual issue was. Instead, the mount command now also provides some textual output.
See https://github.com/koverstreet/bcachefs-tools/issues/308 for an example where mount does not provide any helpful output, even with BCACHEFS_LOG=trace enabled.

mount: print a helpful error message

---

INSTALL.md

This is more in line with the dependencies used to build it for the official Fedora package.

docs: INSTALL: Update list of build dependencies for Fedora

---

doc/bcachefs-principles-of-operation.tex

Adding the upquote package makes the lines
$ getfattr -d -m '^bcachefs\.' filename
$ getfattr -d -m '^bcachefs_effective\.' filename
copy-pastable. Otherwise they get compiled as
$ getfattr -d -m ’^bcachefs\.’ filename
$ getfattr -d -m ’^bcachefs_effective\.’ filename
(slanted quotes) in the pdf.

bcachefs-principles-of-operation.tex: fix slanted quotes in verbatim

---

c_src/cmd_fs.c

It was forcing human readable units even without the -h flag, so use the functions that respect that configuration.

Fix human readable units for compressed data

---

bch_bindgen/src/bkey.rs

BkeySC currently implements a From trait for the bkey_i bindgen/C struct, but not its own direct counterpart; bkey_s_c.   This implements the From trait for bkey_s_c as well.

Implement From<bkey_s_c> trait for BkeySC

---

c_src/cmd_format.c
c_src/libbcachefs.h

Added an option to format with a passphrase file instead of  stdin - since there are already options for unlocking and mounting.
This checks to verify the encryption flag is set, and verifies that no_passphrase isn't set.

Format filesystem with encryption using a passphase file

---

debian/changelog
debian/control

Debian packaging: depend on linux-headers-generic, it will pull in the right one

---

Cargo.toml
src/key.rs

For users that mount the same encrypted bcachefs FS multiple times at boot, this patch makes it so the passphrase is only asked once.
The first commit makes it so `systemd-ask-password` is invoked when stdin is `/dev/null`, instead of using our own passphrase prompting code. This is the case when a bcachefs FS is mounted by systemd: by default, systemd executes the mount helper with stdin set to `/dev/null`.
The second commit fixes a race condition where when multiple `bcachefs mount` commands are executed in parallel, all of them will see that there is no key in the keyring and start an instance of `systemd-ask-password`. We can ask `systemd-ask-password` to try to reuse an existing passphrase in the keyring. `systemd-ask-password` is smart and knows to check again every time another …

Improve systemd-ask-password integration

---

debian/control

bcachefs-kernel-dkms in current shape forces installation of generic linux kernel on Proxmox machines.
Add `pve-headers` as one of acceptable Dependencies so Proxmox-flavoured kernel headers are sufficient for solving dependency graph.

bcachefs-kernel-dkms: Accept pve-headers as one of alternatives to linux-headers
